name: Update Number

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2:00 AM UTC
    - cron: '0 14 * * *' # Runs daily at 2:00 PM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update_number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # Use the required Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Add dependencies here if required

      - name: Run Script
        run: python update_number.py

      - name: Push Changes
        run: |
          git config --global user.name "MuhammadBinSikandar"
          git config --global user.email "m.bin.sikandar@gmail.com"
          git add number.txt
          git commit -m "Automated update via GitHub Actions"
          git push
